### PR TITLE
Recoded Recent Activity

### PR DESCRIPTION
**Pull request by drachels**
Changed the code for recent activity so it works like the code for assignments. No longer uses the log table. Instead uses the journal and journal_entries tables to find recent activity. Changed one language string to be more like the one used for assign, for the recent activity setting.

### CODE REVIEW

**Comment by dmonllao** [comment]
Hi @drachels, it took me a lot of time to return to you, sorry.

I am not convinced about changing 'Show recent activity' setting, people is already using it and journal module students are not supposed to see other student's entries. I think that would be better to keep the setting as it is for backwards compatibility and to keep the module simple.

**Comment by dmonllao** [comment]
I still think the changes are good and I will look at them during next week. Thanks for your contribution.

**Comment by drachels** [comment]
The way I wrote the code is the same way it is for other activities. When a student does some work in their journal, it shows an entry in the Recent Activity block if the Recent activity setting is YES. If the student who wrote the entry clicks the Recent Activity link, then they are taken to their entry. If any other student clicks the same link, they DO NOT go to entry. Instead, they are taken to their own journal, whether they've started it or not.

If the Journal setting for recent activity is left on the default NO, then students never see recent activity except when the activity is created or edited.

Admin or teacher always see recent student activity, no matter the recent activity setting, and if they click a recent activity link, they go to the normal journal report/grading view.

**Comment by dmonllao** [comment]
I've seen that mod_assign is the only module that have a similar setting and works this way, I've checked the git history and it looks to me like a legacy feature, I don't like it to be honest. I've been thinking a lot about it and if we would introduce the show recent activity feature now I would accept the patch as it is because you spent time working on it, but we already have this setting and the setting switches between show/hide journal recent activity. Sorry but, even if the feature was broken we can not now change the setting purpose to a less privacy concerned alternative, people that enabled it may experience an undesired behaviour. I've integrated your patch with an extra commit on top of it to block students to see other students activity. Thanks for your contribution.

**Pull request closed without merging**
