### PR TITLE
DB Performance change counting entries

### PR DESCRIPTION
**Pull request by crazyserver**
Related to https://tracker.moodle.org/browse/CONTRIB-5546 for branch master

### CODE REVIEW

**Comment by dmonllao** [comment]
Thanks for the patches @crazyserver, mod_journal needs hugs like this, just looking a bit at the code I see few places where performance can be improved. I will try to get time today to send a couple more patches improving lib.php functions perf.

Feel free to fetch the last 26 (I guess it is what you are using) version.

**Comment by dmonllao** [comment]
@crazyserver I've pushed a few more performance improvements, basically to the cron routine, they are only available in master, but you should be able to pull them to 2.6, I've done a quick tests and it is all good, but would be awesome if you could try it in a real production site, the performance benefit should be huge.

**Comment by crazyserver** [comment]
Thanks @dmonllao we will test it :+1:

**Comment by dmonllao** [comment]
Cool, let me know if you have any problem, I will release a new version is everything is ok.

**Comment by crazyserver** [comment]
Ok! :+1:  I've rebased the last two commits from master to MOODLE_26 on https://github.com/projectestac/moodle-mod_journal/

We will test it today and try it in production on Tuesday

Ens veiem!!

**Comment by crazyserver** [comment]
It seems to be working, we will try it on Tuesday as well.
BTW, do you mind to rebase the commits for 2.6?

**Comment by dmonllao** [comment]
Sorry Pau, it is too risky to backport these kind of performance improvements to stable branches without testing them properly in master although the changes seems safe. I'm commenting on moodle.org about journal + performance issues, let's see what we get from it.

**Comment by dmonllao** [comment]
https://moodle.org/mod/forum/discuss.php?d=278835

**Comment by crazyserver** [comment]
These are the results on journal/view.php page on the production site:
DB reads/writes: 52/1
DB queries time: 0.07638 secs

And these were the original, before applying the patch:
DB reads/writes: 852/1
DB queries time: 195.92081 secs

We are now trying to get some statistics from cron.

**Comment by crazyserver** [comment]
The cron seems to be working, but We don't know if is having something todo:
Processing module function journal_cron ...... started 10:24:34. Current memory use 31.6MB.
... used 2 dbqueries
... used 0.14121794700623 seconds
done.

**Comment by dmonllao** [comment]
Cool, good results :) 

About your second message, I don't get it, the execution stops after journal_cron?

**Comment by crazyserver** [comment]
No, this is the part of the journal log in cron. But I think that It does not need to do nothing and thats why it only gives 2 dbqueries

**Comment by dmonllao** [comment]
Ah ok, yes, that is an expected behaviour if the cron execution continues
after that. One query should be journal_get_unmailed_graded() and the other
one no idea right now, but yes, it make sense. I also tried it after having
unmailed entries and it worked as expected. Thanks for your help.

**Pull request merged**
